### ISSUE TITLE
Won't compile.

### ISSUE THREAD

**Issue by ApexioDaCoder** [commandblockguy/CEleste#1]
When trying to compile it gives this error: 
``` 
Error: could not generate code within the allowed number of passes.
make: *** [/workspace/CEleste/CEdev/meta/makefile.mk:228: bin/CELESTE.bin] Error 2 
```
I have tried on Linux and Windows and it persists.

**Comment by commandblockguy** [comment]
That's an issue with the linker - you can work around it by replacing every instance of jq in obj/celeste.c.src with jp and then rebuilding.

**Comment by ApexioDaCoder** [comment]
Thank you, that worked.

**Comment by 23marabi** [comment]
Hi, I seem to be having the same issue, but after running `make gfx` and `make`, I don't have any file named `celeste.c.src`.

`make gfx` runs fine, but `make` shows this error:
```
[compiling] src/gfx/atlas.c
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[compiling] src/gfx/mypalette.c
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[compiling] src/profiler.c
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[compiling] src/classic.cpp
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[compiling] src/emu.cpp
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[compiling] src/main.cpp
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[compiling] src/practice.cpp
/home/erin/Projects/TI-84/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /home/erin/Projects/TI-84/CEdev/bin/ez80-clang)
[linking] bin/CELESTE.bin
Error: could not generate code within the allowed number of passes.
make: *** [/home/erin/Projects/TI-84/CEdev/meta/makefile.mk:228: bin/CELESTE.bin] Error 2
```
I'm not sure what the `libtinfo` error is, as I have installed both `ncurses-libtinfo-devel` and `ncurses-libtinfo-libs` which are the only packages my distro has for that.

I've tried replacing every instance of `jq` with `jp` in all the other files within `obj/` but it still doesn't work.

This is all the files I have within the `obj/` folder
![tree](https://user-images.githubusercontent.com/55710109/149681795-83962622-6bd2-4116-87c7-4e216e8759e7.png)

I am running Void Linux (Kernel Version 5.15.14_1). I have the full CE toolchain installed, and have been able to compile applications with it before without issue.

**Comment by adriweb** [comment]
the warning about libtinfo is irrelevant, the solution/workaround posted above should work just fine.

**Comment by commandblockguy** [comment]
Err, sorry, I meant `classic.c.src` - I originally replied on mobile and got the name wrong.

**Comment by 23marabi** [comment]
Ah, thank you. Also turns out the command I was using to find and replace was incorrect as well. Sorry about that, it seems to work fine now.
